-- ============================================================================
-- 20260609180000_seed_demo_world.sql — INTENTIONALLY EMPTY (no-op)
-- ----------------------------------------------------------------------------
-- The demo world this file used to seed was MOVED to supabase/seed/seed.sql on
-- 2026-06-16 (section 5). Reason: it ran as a MIGRATION (before seed.sql) but
-- depended on the GreenLeaf/StonePharm base accounts that seed.sql creates
-- AFTER all migrations — so a fresh `supabase db reset` failed here with
-- "null value in column company_a_id". Demo data now lives only in seed.sql,
-- where it runs once, last, after the base accounts exist.
--
-- This file is kept (not deleted) so the migration history stays consistent
-- with databases that already recorded this migration as applied.
-- ============================================================================
