-- ============================================================================
-- 20260610020000_seed_relationship_demo.sql — INTENTIONALLY EMPTY (no-op)
-- ----------------------------------------------------------------------------
-- Removed 2026-06-16 (Option B). This demo-seed built part of a hand-made demo
-- deal world that depended on fixed UUIDs (relationship 5e64f146…, card
-- 04695a2d…) created ad-hoc on the cloud and never reproducible from files, so
-- a fresh `supabase db reset` could not rebuild it. Decision: keep migrations
-- schema-only; the live demo (Alice/Bob + companies + relationships + chat) is
-- seeded in supabase/seed/seed.sql, and test deals are created through the app's
-- propose→accept→birth flow. File kept (not deleted) so migration history stays
-- consistent with databases that recorded it as applied.
-- ============================================================================
