-- ============================================================================
-- 20260610140000_seed_demo_deal_lines.sql — INTENTIONALLY EMPTY (no-op)
-- ----------------------------------------------------------------------------
-- Removed 2026-06-16 (Option B). Seeded line items onto the hand-made demo card
-- 04695a2d…, a fixed UUID created ad-hoc on the cloud and not reproducible from
-- files. Migrations are now schema-only; demo data lives in supabase/seed/seed.sql
-- and test deals are created through the app. File kept so migration history
-- stays consistent with databases that recorded it as applied.
-- ============================================================================
